Add Romanian translation
SecUSo/privacy-friendly-pedometer pull request #30
Opened 2016-12-29 23:32 UTC by licaon-kter

Translated with https://github.com/LonamiWebs/Stringlate

Do consider #7 too.

2017-01-20 22:26 UTC, licaon-kter commented
Will this merge depend on whether you hire an employee that can speak this language or?

2017-03-20 16:25 UTC, licaon-kter commented
Still discussing, eh? :-|

2017-04-21 16:44 UTC, licaon-kter commented
Should I bother keeping this up to date or?

2017-04-23 19:40 UTC, Yonjuni commented
As we are working on a big update to version 2.0 I would suggest to update the strings after the update, if that's okay. Probably, it's easiest that way.

2023-07-29 17:55 UTC, morckx requested changes
Some problems with XML validity need to be fixed. Also –  no surprise – some strings don't seem to exist anymore.

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +    </string-array>
invalid XML

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +    </string-array>
invalid XML

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +    <string name="action_navigation">Navigare</string>
Some strings here don't exist (anymore).

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +        <item>0.125</item>
invalid XML

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +        <item>90</item>
invalid XML

2023-07-29 17:55 UTC, morckx commented on app/src/main/res/values-ro/strings.xml
> +        <item>0.5</item><!-- step length in meters -->
invalid XML

2024-09-10 14:56 UTC, closed without merging